import numpy as np

import calculate_funcs as calf


BAUDRATE = 115200
DEVICENAME = '/dev/ttyUSB0'
PROTOCOL_VERSION = 2.0
DXL_MIN_POS_VALUE = 0
DXL_MAX_POS_VALUE = 4094
DXL_PLOFILE_VELOCITY = 30000
DXL_PLOFILE_ACCELERATION = 50

L1 = 478.75
L2_DEFAULT = 308.0
L_HAND = 126

THETA2_RANGE = np.radians(np.array([0, 170]))
THETA_HAND_UP = np.radians(0)
THETA_HAND_DOWN = np.radians(-90)
L2_HAND_UP = L2_DEFAULT + L_HAND * np.cos(THETA_HAND_UP)
L2_HAND_DOWN = L2_DEFAULT + L_HAND * np.cos(THETA_HAND_DOWN)

SHERE_AREA_X = 697.5

ACC_TIME = 0.4
MOVE_TIME = 0.7
MAX_VEL, MAX_ACC = calf.calc_lspb_params(
    ACC_TIME, MOVE_TIME
)

FPS = 60

BUTTON_WORKSPACE_TRIGER = 4
BUTTON_SHOOTINGAREA_TRIGER = 5
BUTTON_P1 = 1
BUTTON_P2 = 2
BUTTON_P3 = 3
BUTTON_P4 = 0
BUTTON_P5 = (0, 1)
BUTTON_P6 = (1, 1)
BUTTON_P7 = (0, -1)
BUTTON_P8 = (1, -1)