import numpy as np

import calculate_funcs as calf
import dynamixel_funcs as dxlf


RASPICO_DEVNAME = '/dev/ttyACM0'
RASPICO_BAUDRATE = 9600

BAUDRATE = 2000000
DEVICENAME = '/dev/ttyUSB0'
PROTOCOL_VERSION = 2.0
DXL_MIN_POS_VALUE = 0
DXL_MAX_POS_VALUE = 4094
DXL_PLOFILE_VELOCITY = 30000
DXL_PLOFILE_ACCELERATION = 100
MOVE_TO_HOME_PLOFILE_VEL = 1000
MOVE_TO_HOME_PLOFILE_ACC = 30

L1 = 478.75
L2 = 308.0
L_HAND = 137.04

THETA2_RANGE = np.radians(np.array([0, 170]))
THETA_HAND_UP = np.radians(0)
THETA_HAND_DOWN = np.radians(60)
DXL_POS_HAND_UP = dxlf.calc_dxl_pos_from_theta(THETA_HAND_UP, DXL_MAX_POS_VALUE)
DXL_POS_HAND_DOWN = dxlf.calc_dxl_pos_from_theta(THETA_HAND_DOWN, DXL_MAX_POS_VALUE)
L2_HAND_UP = L2 + L_HAND * np.cos(THETA_HAND_UP)
L2_HAND_DOWN = L2 + L_HAND * np.cos(THETA_HAND_DOWN)

SHERE_AREA_X = 697.5

ACC_TIME = 0.3
MOVE_TIME = 0.8
MAX_VEL, MAX_ACC = calf.calc_lspb_params(
    ACC_TIME, MOVE_TIME
)

FPS = 80
JOYSTICK_DEDZONE_THRESH = 0.1

# ボタンコンフィグ系
BUTTON_VACUME_START = 12
BUTTON_VACUME_END = 11
BUTTON_WORKSPACE_TRIGER = 4
BUTTON_SHOOTINGAREA_TRIGER = 5
BUTTON_HANDS_UP = 8
BUTTON_HANDS_DOWN = 9
AXIS_SPEED_ADJUST = 5
AXIS_X = 1
AXIS_Y = 0
BUTTON_P1 = 1
BUTTON_P2 = 2
BUTTON_P3 = 3
BUTTON_P4 = 0
BUTTON_P5 = (0, 1)
BUTTON_P6 = (1, 1)
BUTTON_P7 = (0, -1)
BUTTON_P8 = (1, -1)